### ISSUE TITLE
Odd Behavior with Directive String

### ISSUE THREAD

**Issue by iancallahan** [ohseesoftware/laravel-vite-manifest#1]
Hello! Thanks for this package. This is more of a head's up for anyone else who may be experiencing this.

I have an odd set up where I'm wedging an SPA into an existing website. So my entry file is 'index.html'.

Here's the odd thing. If I use: 
`@vite('index.html')`

I get an error:
`syntax error, unexpected 'index' (T_STRING), expecting ')' `

If I use double quotes, the string gets passed but it includes the quotes as html entities:
`&quot;index.html&quot;`

But the following, without quotes, works like a charm:
`@vite(index.html)`

It's probably some peculiar thing about MacOS as I've encountered this issue running locally using Valet. 

Thanks again.

**Comment by owenconti** [comment]
@iancallahan My blade directive is including the quotes automatically, so I think the README is incorrect
